[package]
name = "unify"
version = "0.6.1"
entrypoint = "lib.typ"
authors = ["Christopher Hecker"]
repository = "https://github.com/ChHecker/unify"
license = "MIT"
description = "Format numbers, units, and ranges correctly."
exclude = ["examples"]
